#!/bin/bash

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# STOP SYSTEMD SERVICE
#=================================================
ynh_script_progression "Stopping $app's systemd service..."

ynh_systemctl --service=$app --action="stop" --log_path="systemd"

#=================================================
# DOWNLOAD, CHECK AND UNPACK SOURCE
#=================================================
ynh_script_progression "Upgrading source files..."

ynh_setup_source --dest_dir="$install_dir"

chmod +x $install_dir/bin/runSafe.sh

#=================================================
# UPDATE A CONFIG FILE
#=================================================
ynh_script_progression "Updating configuration..."

ynh_nodejs_install

ynh_config_add_nginx

ynh_config_add_systemd

yunohost service add $app --description "Collaborative spreadsheet editor" --log="/var/log/$app/$app.log"

#=================================================
# INSTALL ETHERCALC
#=================================================
ynh_script_progression "Building EtherCalc... (this will take some time and resources!)"

pushd "$install_dir"
	ynh_safe_rm "$install_dir/package-lock.json"
	ynh_hide_warnings ynh_exec_as_app npm install -g ethercalc
	ynh_hide_warnings ynh_exec_as_app npm i zappajs
popd

#=================================================
# START SYSTEMD SERVICE
#=================================================
ynh_script_progression "Starting $app's systemd service..."

ynh_systemctl --service=$app --action="start" --log_path="systemd"

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Upgrade of $app completed"
